dataloader:
  num_workers: 0
  batch_size: 2
  dataset:
    name: 'pixel'
    data_folder: '../../../OneDrive/NeuralMorphology/Simulations/Simulations_16bit_Size1024/TrainingKit'
    ann_file: 'dataloader/annotation/dataset4.pkl'

solver:
  loss: dice
  optimizer: 'sgd'
  max_epoch: 20
  base_lr: 0.02
  momentum: 0.9
  weight_decay: 1.0e-5
  lr_scheduler: 'cosine'
  T_0: 200
  T_mul: 1

model:
  name: 'unet_att'
  device: 'none'
  mode: 'train'
  ckpt: None

load_from: null
output_dir: '../../../OneDrive/NeuralMorphology/Simulations/Simulations_16bit_Size1024/output/ex8'