dataloader:
  num_workers: 0
  batch_size: 16
  dataset:
    name: 'pixel'
    data_folder: '/home/idies/workspace/ssec_neural_morphology/Simulations_16bit_Size3334/TrainingKit'
    ann_file: 'dataloader/annotation/dataset7.pkl'

solver:
  loss: dice
  optimizer: 'sgd'
  max_epoch: 100
  base_lr: 0.02
  momentum: 0.9
  weight_decay: 1.0e-5
  lr_scheduler: 'cosine'
  T_0: 200
  T_mul: 1

model:
  name: 'unet_att'
  device: 'none' # 'cuda' for GPU, 'mps' for Mac, may leave 'none' (identified on-fly) or specify like 'cuda:0'
  train: False # True to train, False to load pre-trained model and then test
  test: True # True to test the model after training
  ckpt: None
  tile_assembly: 'nn' # 'nn' or 'mean' or 'max'
  threshold: 'none' # 'none' or number between 0 and 1
  thresh_calc_method: 'global' # 'global' or 'tiles'
  thresh_one_cc: True # Lower threshold to get only one connected component

load_from: null
output_dir: '/home/idies/workspace/ssec_neural_morphology/Simulations_16bit_Size3334/output/ex7/'
