dataloader:
  num_workers: 0
  batch_size: 2
  dataset:
    name: 'pixel'
    data_folder: '../../../OneDrive/Neural Morphology - Adkins - Yale/Simulations/Simulations_16bit_Size1024/dataset/Starting Kit Pixel'
    ann_file: 'dataloader/annotation/dataset3.pkl'

solver:
  loss: dice
  optimizer: 'sgd'
  max_epoch: 20
  base_lr: 0.02
  momentum: 0.9
  weight_decay: 1.0e-5
  lr_scheduler: 'cosine'
  T_0: 200
  T_mul: 1

model:
  name: 'unet_att'
  device: 'mps'
  mode: 'train'
  ckpt: None

load_from: 'output/ex3/ckpt_init10.pth'
output_dir: 'output/ex3/'