dataloader:
  num_workers: 4
  batch_size: 2
  dataset:
    name: 'pixel'
    data_folder: '../../../OneDrive/NeuralMorphology - Adkins - Yale/Simulations/Simulations_8bit_Size1000/Dataset/TrainingKit/'
    ann_file: 'dataloader/annotation/dataset2.pkl'

solver:
  loss: dice
  optimizer: 'sgd'
  max_epoch: 10
  base_lr: 0.02
  momentum: 0.9
  weight_decay: 1.0e-5
  lr_scheduler: 'cosine'
  T_0: 200
  T_mul: 1

model:
  name: 'unet_att'
  device: 'mps'
  mode: 'train'
  ckpt: None

load_from: null
output_dir: 'output/ex2/'