dataloader:
  num_workers: 0
  batch_size: 16
  dataset:
    name: 'pixel'
    data_folder: '/home/idies/workspace/ssec_neural_morphology/Simulations_16bit_Size3334/TrainingKit'
    ann_file: 'dataloader/annotation/dataset7.pkl'

solver:
  loss: dice
  optimizer: 'sgd'
  max_epoch: 100
  base_lr: 0.02
  momentum: 0.9
  weight_decay: 1.0e-5
  lr_scheduler: 'cosine'
  T_0: 200
  T_mul: 1

model:
  name: 'unet_att'
  mode: 'train'
  ckpt: None
  tile_assembly: 'nn' # 'mean', 'max' or 'nn'
  threshold: 0.69 # 'none' or number between 0 and 1

load_from: null
output_dir: '/home/idies/workspace/ssec_neural_morphology/Simulations_16bit_Size3334/output/ex7/'
